### ISSUE TITLE
Autoshutdown log isn't displayed in WebUI

### ISSUE THREAD

**Issue by yubiuser** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#41]
Hey,

I just updated from OMV 3 --> OMV 4.0.91 with Debian 9 and Kernel 4.13. Autoshutdown 4.02. is installed and workes fine.
But the log of autoshutdown isn't displayed completely anymore in "Logs/Autoshutdown" in the WebUI.

It is logging to /var/logs/autoshutdown.log (See attachment)
[autoshutdown.log](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/files/1482914/autoshutdown.log)

The only lines that are displayed in the WebUI are those, with "omv logger: autoshutdown.sh" but not those with "omv root: autoshutdown".

apt-get remove --purge openmediavault-autoshutdown and reinstallation didn't solve the problem.

Any suggestions?

Thanks

**Comment by ryecoaaron** [comment]
For some reason, the regex for the log display needs to be fixed.  It has probably been broken a long time.  I will look at this when I get a chance.

**Comment by yubiuser** [comment]
Thanks.

**Comment by belierzz** [comment]
I can second the above: the missing Logs/Autoshutdown entries can be found in Logs/Boot!?

**Comment by jonathanmmm** [comment]
Thanks, I have the same problem, through ssh I can see everything but in the GUI I can only see:
Initilize logging to local 6
X Version 0.9.9.10
XXXXXXXXXXXXXXXXXXXXXXXXXXX...
XXXXXXXXXXXXXXXXXXXXXXXXXXX...
XXXXXXXXXXXXXXXXXXXXXXXXXXX...

OMV 4.1.0-1
OMV Extras 4.1.2
Kernel 4.14.0-0.bpo.3-adm64

**Comment by Ansem93** [comment]
I checked, you can find the autoshutdown log inside the "boot" log, not sure why :(

**Comment by ErdnussFlipS** [comment]
> For some reason, the regex for the log display needs to be fixed. It has probably been broken a long time. I will look at this when I get a chance.
@ryecoaaron Where I can find the regex to fix this issue?

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/blob/master/usr/share/openmediavault/engined/inc/90autoshutdown.inc

**Comment by ErdnussFlipS** [comment]
Thx.

I will suggest this regex: `^(\S+\s+\d+\s+\S+)\s+.*\s+(?:logger|root): autoshutdown\S+:\s+(\S+):\s+(.*)$`

You can check this with these webapps https://www.debuggex.com/ or https://regex101.com/

In the next days I will create a pull requests for that.

**Comment by belierzz** [comment]
Sorry, doesn't work for me. Nothing changed. Still inside "boot" log.

**Comment by yubiuser** [comment]
Which OMV version are you using? 
For me it's working perfectly since it has been fixed. Using OMV 4.1.8.2

**Comment by ErdnussFlipS** [comment]
@belierzz do you rebuild it on your own? I think there was no new release for the plugin since this fix.

**Comment by belierzz** [comment]
I'm on OMV 4.1.8.2, Debian 9 netinstall and OMV on top several releases ago. I've made all updates via WebGUI. Never touched the plugins themselves but got them via omv-extras at initial install. Really strange. I even uninstalled and re-installed the autoshutdown-plugin, version shown is 4.0.3. 
Now I have checked 90autoshutdown.inc and still the old code present. Updated manually and works fine.

**Comment by ryecoaaron** [comment]
4.0.4 is in the repo now.

**Comment by luisbarreto** [comment]
Autoshutdown logs are still appearing on "boot" log on a Raspberry Pi.
Running 4.1.17-1. Can this be fixed in any way?
